<?php

declare(strict_types=1);

namespace Sakoo\Framework\Core\Doc\Formatters;

use Sakoo\Framework\Core\Doc\Object\NamespaceObject;

/**
 * Table-of-contents formatter that produces a Markdown navigation sidebar.
 *
 * Renders one bullet-point entry per namespace in the form:
 *
 *   * [ShortName](#-anchor)
 *
 * where ShortName strips the leading 'Sakoo\Framework\Core\' prefix for readability
 * and the anchor is derived by lowercasing the full namespace and replacing spaces
 * and backslashes with hyphens, matching GitHub wiki anchor conventions.
 *
 * Intended for use as a _Sidebar.md file in GitHub wikis generated by DocGenCommand.
 */
class TocFormatter extends Formatter
{
	/**
	 * Emits one Markdown list item per namespace and returns the accumulated sidebar string.
	 *
	 * @param NamespaceObject[] $namespaces
	 */
	public function format(array $namespaces): string
	{
		foreach ($namespaces as $namespace) {
			$this->markup->write(
				'* [' . str_replace('Sakoo\Framework\Core\\', '', $namespace->getName()) . '](#-' . strtolower(str_replace([' ', '\\'], ['-', ''], $namespace->getName())) . ')' . PHP_EOL
			);
		}

		return (string) $this->markup;
	}
}
